# Generated by Django 6.0.3 on 2026-04-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_priority_urgency_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="course",
        ),
        migrations.RemoveField(
            model_name="task",
            name="estimated_minutes",
        ),
    ]
