# Generated by Django 6.0.4 on 2026-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_estimated_minutes_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
